/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import task1.runTask1
import task2.runTask2
import kotlin.io.path.Path

class App {
    val greeting: String
        get() {
            return "Module 4 tasks 1-2"
        }
}

fun main(args: Array<String>) {
    when (args.firstOrNull()?.lowercase()) {
        "task1", "1" -> runTask1()
        "task2", "2" -> {
            val directory = args.getOrNull(1)?.let(::Path) ?: Path(".")
            val timeoutSeconds = args.getOrNull(2)?.toLongOrNull() ?: 5L
            runTask2(directory, timeoutSeconds)
        }
        else -> {
            println(App().greeting)
            println("Запуск:")
            println("  ./gradlew run --args=\"task1\"")
            println("  ./gradlew run --args=\"task2 <directory> <timeoutSeconds>\"")
        }
    }
}
