/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import com.github.jengelman.gradle.plugins.shadow.transformers.AppendingTransformer

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.shadow)
    application
}

repositories {
    mavenCentral()
}

dependencies {
    // Ktor Core & Netty Engine
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)
    
    // Exposed + PostgreSQL
    implementation(libs.exposed.core)
    implementation(libs.exposed.dao)
    implementation(libs.exposed.jdbc)
    implementation(libs.postgresql)
    implementation(libs.exposed.java.time)
    
    // HikariCP (Connection Pool)
    implementation(libs.hikaricp)
    
    // Bcrypt
    implementation(libs.bcrypt)
    
    // Swagger UI
    implementation(libs.ktor.server.swagger)

    // JSON Serialization
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)

    // Authentication (JWT)
    implementation(libs.ktor.server.auth.jwt)

    // Logging
    implementation(libs.ktor.server.call.logging)
    implementation(libs.logback.classic)

    // Тестирование
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation(libs.junit.jupiter.engine)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    
    mainClass = "org.example.AppKt" 
}


tasks.withType<ShadowJar> {
    mergeServiceFiles() // Для работы некоторых внутренних механизмов SPI
    transform(AppendingTransformer::class.java) {
        resource = "reference.conf" // Собираем все конфиги Ktor в один
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}