/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ktor)
    application
}

repositories {
    mavenCentral()
}

dependencies {
    // Тестирование
    testImplementation(libs.kotlin.test)
    testImplementation(libs.junit.jupiter.engine)
    testRuntimeOnly(libs.junit.platform.launcher)

    // Ядро и движок сервера (Netty)
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)

    // Авторизация (JWT)
    implementation(libs.ktor.server.auth)
    implementation(libs.ktor.server.auth.jwt)

    // Сериализация (JSON)
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)

    // Логирование запросов
    implementation(libs.ktor.server.call.logging)
    implementation(libs.logback.classic)
}

java {
    toolchain {
        
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}